name: Test action
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup # テストの準備
        run: date > foo.md
      - name: Exercise # テスト対象コードの実行
        id: exercise
        uses: ./
        with:
          message: Test
